settings:
  title: 'Galaxy Nexus Status Page'
  url: 'https://status.galaxynex.us' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Some Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-galaxynex-us # unique identifier
    name: Galaxy Nexus Home Page
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://www.galaxynex.us/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: panel-galaxynex-us
    name: Galaxy Nexus Panel
    description: 'Our own custom Panel.'
    url: 'https://au.dev.galaxynex.us'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: clients-galaxynex-us
    name: Galaxy Nexus Client Portal
    url: 'https://clients.galaxynex.us/'
    method: GET
    expectStatus: 200
